"""PowerPoint report generation."""

from typing import Dict, Iterable

from pptx import Presentation


def _add_title_slide(prs: Presentation, title: str, subtitle: str = "") -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    if subtitle:
        slide.placeholders[1].text = subtitle


def _add_bullet_slide(
    prs: Presentation, heading: str, bullets: Iterable[str]
) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = heading
    body = slide.shapes.placeholders[1].text_frame
    body.clear()
    for index, bullet in enumerate(bullets):
        paragraph = body.paragraphs[0] if index == 0 else body.add_paragraph()
        paragraph.text = bullet


def build_ppt(
    title: str,
    aggregated: Dict[str, object],
    out_path: str = "report.pptx",
) -> str:
    prs = Presentation()
    _add_title_slide(prs, title, "Generated by KapexAI")

    swot = aggregated.get("swot") or {}
    if isinstance(swot, dict):
        bullets = [
            f"{key.title()}: {', '.join(swot.get(key) or [])}"
            for key in ("strengths", "weaknesses", "opportunities", "threats")
        ]
        _add_bullet_slide(prs, "SWOT Analysis", bullets)

    porter = aggregated.get("porter") or {}
    if isinstance(porter, dict):
        bullets = [
            f"{key.replace('_', ' ').title()}: {value}"
            for key, value in porter.items()
            if key != "topic"
        ]
        _add_bullet_slide(prs, "Porter Five Forces", bullets)

    financial = aggregated.get("financial") or {}
    if isinstance(financial, dict):
        bullets = [
            f"{key.replace('_', ' ').title()}: {value}"
            for key, value in financial.items()
            if key != "topic"
        ]
        _add_bullet_slide(prs, "Financial Summary", bullets)

    prs.save(out_path)
    return out_path
